# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('url', models.URLField()),
                ('first_release_date', models.DateTimeField()),
                ('popularity', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('summary', models.TextField(blank=True, null=True)),
                ('total_rating', models.FloatField(blank=True, null=True)),
                ('total_rating_count', models.PositiveIntegerField(blank=True, null=True)),
                ('igdb', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('pcid', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('asin', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('epid', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='basegame',
            name='collections',
            field=models.ManyToManyField(blank=True, to='games.Collection'),
        ),
        migrations.AddField(
            model_name='basegame',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Franchise'),
        ),
        migrations.AddField(
            model_name='basegame',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='games.Keyword'),
        ),
        migrations.AddField(
            model_name='basegame',
            name='platforms',
            field=models.ManyToManyField(to='consoles.Platform'),
        ),
        migrations.AddField(
            model_name='basegame',
            name='themes',
            field=models.ManyToManyField(blank=True, to='games.Theme'),
        ),
    ]
