# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='EbayListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('country', models.TextField()),
                ('location', models.TextField()),
                ('url', models.URLField()),
                ('condition', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.SlugField()),
                ('url', models.URLField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField()),
                ('total_rating', models.FloatField()),
                ('total_rating_count', models.PositiveIntegerField()),
                ('first_release_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('collections', models.ManyToManyField(blank=True, null=True, to='games.Collection')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='games.Keyword'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='consoles.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, to='games.Theme'),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
