# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='total_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_rating_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
