# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170720_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basegame',
            old_name='platforms',
            new_name='consoles',
        ),
    ]
