# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170722_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basegame',
            name='slug',
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='slug', max_length=128),
            preserve_default=False,
        ),
    ]
