# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20170724_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='edition',
            field=models.CharField(default='Original', max_length=32),
        ),
    ]
