# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='asin',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='epid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
