# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20170804_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='asin',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='epid',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
