# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20170808_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='verified',
        ),
        migrations.AddField(
            model_name='game',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
