# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20170808_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basegame',
            name='consoles',
        ),
        migrations.RemoveField(
            model_name='basegame',
            name='first_release_date',
        ),
        migrations.RemoveField(
            model_name='basegame',
            name='igdb',
        ),
        migrations.RemoveField(
            model_name='basegame',
            name='themes',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='igdb',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='igdb',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pcid',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='igdb',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
