# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gameboyz.games.utils


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20170818_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=gameboyz.games.utils.user_game_image_upload)),
                ('gamelisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameListing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
