# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_gamelistingimage_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basegame',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='basegame',
            name='total_rating',
        ),
        migrations.RemoveField(
            model_name='basegame',
            name='total_rating_count',
        ),
    ]
