# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_gamelisting_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelisting',
            name='uuid',
        ),
    ]
