# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_auto_20171027_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameListingImage',
        ),
    ]
