# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_auto_20171028_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='basegame',
            new_name='gametitle',
        ),
    ]
