# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 12:42
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170817_0301'),
    ]

    operations = [
        UnaccentExtension(),
    ]
