# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platform',
            new_name='BaseConsole',
        ),
    ]
