# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseconsole',
            name='igdb',
        ),
    ]
