# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consoles', '0004_console_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('condition', models.CharField(max_length=32)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.Console')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
