# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='url',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='url',
        ),
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Platform'),
        ),
    ]
