# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 13:57
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171025_1242'),
    ]

    operations = [
        TrigramExtension(),
    ]
