# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import games.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consoles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=256, unique=True)),
                ('edition', models.CharField(blank=True, max_length=32, null=True)),
                ('asin', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('epid', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=games.utils.image_path_rename)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameListing',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('Complete In Box', (('cibvgood', 'Very Good'), ('cibgood', 'Good'), ('cibacceptable', 'Acceptable'))), ('Loose', (('loosevgood', 'Very Good'), ('loosegood', 'Good'), ('looseacceptable', 'Acceptable')))], max_length=32)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=games.utils.user_game_image_upload)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gamelisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameListing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Franchise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='gametitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameTitle'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.Platform'),
        ),
    ]
