# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Franchise'),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='related_games',
            field=models.ManyToManyField(blank=True, null=True, related_name='_game_related_games_+', to='games.Game'),
        ),
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
