# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20171104_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='related_games',
            field=models.ManyToManyField(blank=True, related_name='_game_related_games_+', to='games.Game'),
        ),
    ]
