# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
        ('games', '0002_auto_20170722_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='console',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consoles.BaseConsole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='edition',
            field=models.CharField(default='original', max_length=32),
        ),
    ]
