# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20171104_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametitle',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gametitle',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='Default Name', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(default='http://default.com'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GameTitle',
        ),
    ]
