# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20170815_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='console',
            new_name='baseconsole',
        ),
    ]
