# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_gamelistingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelistingimage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
