# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20171026_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basegame',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='basegame',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='game',
            name='published',
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='edition',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
