# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_remove_gamelisting_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelisting',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
