# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_auto_20171026_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelisting',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
