# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_auto_20171026_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelisting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
