# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_auto_20171027_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelisting',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamelisting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamelistingimage',
            name='gamelisting',
        ),
        migrations.DeleteModel(
            name='GameListing',
        ),
    ]
