# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_gamelisting_gamelistingimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseGame',
            new_name='GameTitle',
        ),
    ]
