# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_remove_gamelisting_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelisting',
            name='game',
            field=models.ForeignKey(default=789, on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
            preserve_default=False,
        ),
    ]
