# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consoles', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=64)),
                ('url', models.URLField(db_index=True, unique=True)),
                ('condition', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('sold', models.DateTimeField()),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.Console')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=64)),
                ('url', models.URLField(db_index=True, unique=True)),
                ('condition', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('sold', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
