# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20170731_0649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='GameSale',
        ),
    ]
