# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_consolesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesale',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
