# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170731_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='condition',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='sale',
            name='location',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
