# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170731_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='url',
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
